# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/uav/xsub1/test_A_joint.npy
  label_path: ./data/uav/xsub1/test_label_A.npy
  debug: False

# model
model: model.tegcn.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.uav.Graph
  graph_args:
    labeling_mode: 'spatial'

# test
phase: test
device: [0,1,2,3]
test_batch_size: 128 #256
#weights: ./runs/ntu_cs_agcn_joint-49-31300.pt uav-48-25137.pt
weights: ./runs/uav-43-22572.pt
save_score: True
work_dir: ./work_dir/ntu/xview/test_joint_b
model_saved_name: ./runs/test_joint_b